// @ts-check

import { WalkThrough } from '../class/WalkThrough.mjs';
import { ForInSync } from '../function/ForInSync.mjs';
import { ForOfSync } from '../function/ForOfSync.mjs';
import { IsTypeOf } from '../function/IsTypeOf.mjs';
import { WC_createElement_bind } from './bindings/WC_createElement_bind.mjs';
import { WC_createNamedSlot } from './bindings/WC_createNamedSlot.mjs';

/**
 * @import {ArrayToKeys} from '../typehints/ArrayToKeys.mjs'
 * @import {WC_TagName_type} from './common/WC_TagName_type.mjs'
 */

/**
 * @description
 * - Generates a base class for Web Component definitions.
 * - Note: This generator does not support `connectedMoveCallback`.
 * For the needs of opting in to [connectedMoveCallback](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) functionality, use [WC_extendsB](#wc_extendsb) instead.
 * - This class relies heavily on complex type inference which can cause issues, during declaration file generation. To avoid "circular type" errors or build failures, set the following in your `tsconfig.json`:
 * ```json
 * {
 * 	"compilerOptions": {
 * 		"declaration": false
 * 	}
 * }
 * ```
 * - By disabling `declaration`, you prevent the TypeScript compiler from attempting to resolve and export the complex recursive type definitions generated by this factory;
 * @template {new (...args: any[]) => HTMLElement} BASE_CONSTRUCTOR
 * @template {{
 * 	class?:string;
 * 	style?:string;
 *  observedAttributes?: readonly string[];
 *  namedSlots?: readonly string[];
 * }} STATICMEM
 * @template {(BASE_CONSTRUCTOR) & {
 * 	tagName: string;
 * 	extendIs: string;
 * 	observedAttributes?: STATICMEM["observedAttributes"];
 * 	namedSlots?: STATICMEM["namedSlots"];
 * }} CREATEARGS
 * @template { (new (...args: any[]) => InstanceType<BASE_CONSTRUCTOR> & {
 * 		setObservedAttributes(attributes:Partial<
 * 			Record<ArrayToKeys<STATICMEM["observedAttributes"]extends readonly string[]
 * 				? STATICMEM["observedAttributes"]
 * 				:never>,
 * 			string>
 * 		>):void;
 *    adoptedCallback():void;
 *    connectedCallback():void;
 *    disonnectedCallback():void;
 * 		attributeChangedCallback(name:ArrayToKeys<STATICMEM["observedAttributes"]extends readonly string[]?STATICMEM["observedAttributes"]:never>, oldValue:string|null, newValue:string|null): void;
 * 		ON:<OBJ extends any & {
 * 				onConnected?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["connected"];
 * 				onDisconnected?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["disconnected"];
 * 				onAdopted?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["adopted"];
 * 				onAttributeChanged?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["attributeChanged"];
 * 			}>
 * 		(obj:OBJ, callbacks?:
 * 			{
 * 				connected?:(obj:OBJ)=>void;
 * 				disconnected?:(obj:OBJ)=>void;
 * 				adopted?:(obj:OBJ)=>void;
 * 				attributeChanged?:(
 * 					obj:OBJ,
 * 					name:STATICMEM["observedAttributes"]extends readonly string[]
 * 						? ArrayToKeys<STATICMEM["observedAttributes"]>
 * 						: never,
 * 					oldValue:string|null,
 * 					newValue:string|null
 * 				)=>void;
 * 			})=>OBJ;
 *  }) & {
 * 		tagName:string;
 * 		extendIs:string;
 *  	namedSlots: STATICMEM["namedSlots"];
 *  	observedAttributes: STATICMEM["observedAttributes"];
 * 		createNamedSlot: typeof WC_createNamedSlot<STATICMEM>;
 * 		define:<TAG extends string, CLASSREF extends CREATEARGS>
 * 			(
 * 				tagName:WC_TagName_type<TAG>,
 * 				classRef:CLASSREF,
 * 				elementDefinitionOptions?:ElementDefinitionOptions,
 * 			)=>ReturnType<typeof WC_createElement_bind<CLASSREF>>;
 * 	}
 * } RET
 * @param {BASE_CONSTRUCTOR} Base
 * @param {STATICMEM} [staticMember]
 * @returns {RET}
 * @example
 * export MyWebComponent extends WC_extendsA(HTMLElement, {...options}){
 * 	static create = this.define('my-webcomponent');
 * }
 */
export function WC_extendsA(Base, staticMember = /** @type {any} */ ({})) {
	const { class: class_ = '', style = '', observedAttributes = [], namedSlots = [] } = staticMember;
	class MyClass extends Base {
		static observedAttributes = observedAttributes;

		/** @type {Set<()=>void>} */
		#setOfConnected = new Set();
		/** @type {Set<()=>void>} */
		#setOfDisconnected = new Set();
		/** @type {Set<()=>void>} */
		#setOfAdopted = new Set();
		/** @type {Set<(name:string, oldValue:string|null, newValue:string|null)=>void>} */
		#setOfAttributeChanged = new Set();

		/**
		 * @description
		 * - wrapper helper to handle returned to be assigned property on `WebComponent` lifecycle callbacks;
		 * @template {Object} OBJ
		 * @param {OBJ & {
		 * 	onConnected?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["connected"];
		 * 	onDisconnected?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["disconnected"];
		 * 	onAdopted?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["adopted"];
		 * 	onAttributeChanged?: NonNullable<Parameters<InstanceType<RET>["ON"]>[1]>["attributeChanged"];
		 * }} obj
		 * @param {Object} [callbacks]
		 * @param {(obj:OBJ)=>void} [callbacks.connected]
		 * @param {(obj:OBJ)=>void} [callbacks.disconnected]
		 * @param {(obj:OBJ)=>void} [callbacks.adopted]
		 * @param {(
		 * 	obj:OBJ,
		 * 	name:STATICMEM["observedAttributes"]extends readonly string[]
		 * 		? ArrayToKeys<STATICMEM["observedAttributes"]>
		 * 		: never,
		 * 	oldValue:string|null,
		 * 	newValue:string|null
		 * )=>void} [callbacks.attributeChanged]
		 * @returns {OBJ}
		 * @example
		 * // inside WebComponent context
		 * #mySignal = this.ON(createSignalFromExternalLib(0),{
		 * 	disconnected:(s)=>{
		 * 		s.cleanup(); // <-or any equivalent;
		 * 	},
		 * });
		 * //
		 */
		ON(obj, callbacks = {}) {
			const { connected, disconnected, adopted, attributeChanged } = callbacks;
			if (connected) {
				this.#setOfConnected.add(() => {
					connected(obj);
				});
			}
			if ('onConnected' in obj && IsTypeOf(obj.onConnected, 'function')) {
				this.#setOfConnected.add(obj.onConnected);
			}
			if (disconnected) {
				this.#setOfDisconnected.add(() => {
					disconnected(obj);
				});
			}
			if ('onDisconnected' in obj && IsTypeOf(obj.onDisconnected, 'function')) {
				this.#setOfDisconnected.add(obj.onDisconnected);
			}
			if (adopted) {
				this.#setOfAdopted.add(() => {
					adopted(obj);
				});
			}
			if ('onAdopted' in obj && IsTypeOf(obj.onAdopted, 'function')) {
				this.#setOfAdopted.add(obj.onAdopted);
			}
			if (attributeChanged) {
				this.#setOfAttributeChanged.add((name, oldValue, newValue) => {
					attributeChanged(
						obj,
						// @ts-expect-error
						name,
						oldValue,
						newValue,
					);
				});
			}
			if ('onAttributeChanged' in obj && IsTypeOf(obj.onAttributeChanged, 'function')) {
				this.#setOfAttributeChanged.add(obj.onAttributeChanged);
			}
			return obj;
		}
		/**
		 * @protected
		 */
		connectedCallback() {
			// @ts-expect-error
			if (super.connectedCallback) {
				// @ts-expect-error
				super.connectedCallback();
			}
			if (class_) {
				this.setAttribute('class', class_);
			}
			if (style) {
				this.setAttribute('style', style);
			}
			WalkThrough.set(this.#setOfConnected, (cb) => cb());
			ForOfSync(observedAttributes, (key) => {
				this.attributeChangedCallback(key, null, this.getAttribute(key));
			});
		}

		/**
		 * @protected
		 */
		disconnectedCallback() {
			// @ts-expect-error
			if (super.disconnectedCallback) {
				// @ts-expect-error
				super.disconnectedCallback();
			}
			WalkThrough.set(this.#setOfDisconnected, (cb) => cb());
		}

		/**
		 * @protected
		 */
		adoptedCallback() {
			// If super has a connectedCallback, it's good practice to call it
			// @ts-expect-error
			if (super.adoptedCallback) {
				// @ts-expect-error
				super.adoptedCallback();
			}
			WalkThrough.set(this.#setOfAdopted, (cb) => cb());
		}

		/**
		 * @protected
		 * @param {string} name
		 * @param {string | null} oldValue
		 * @param {string | null} newValue
		 */
		attributeChangedCallback(name, oldValue, newValue) {
			// @ts-expect-error
			if (super.attributeChangedCallback) {
				// @ts-expect-error
				super.attributeChangedCallback(name, oldValue, newValue);
			}
			WalkThrough.set(this.#setOfAttributeChanged, (cb) => cb(name, oldValue, newValue));
		}
		/**
		 * @description
		 * @type {InstanceType<RET>["setObservedAttributes"]}
		 */
		setObservedAttributes = (attributes) => {
			ForInSync(attributes, (key, value) => {
				this.setAttribute(key.toString(), value ?? '');
			});
		};
		/**
		 * @protected
		 * @type {string}
		 */
		static tagName;
		/**
		 * @protected
		 * @type {keyof HTMLElementTagNameMap}
		 */
		static extendIsValue;
		/**
		 * @protected
		 * @type {readonly string[]|undefined}
		 */
		static namedSlots = namedSlots;
		/**
		 * @description
		 * @protected
		 */
		static createNamedSlot = WC_createNamedSlot;
		/**
		 * @description
		 * - to be called before calling `ClassRef.new`;
		 * @type {<TAG extends string, CLASSREF extends CREATEARGS>
		 * 			(
		 * 				tagName:WC_TagName_type<TAG>,
		 * 				classRef:CLASSREF,
		 * 				elementDefinitionOptions?:ElementDefinitionOptions,
		 * 			)=>ReturnType<typeof WC_createElement_bind<CLASSREF>>
		 * 	}
		 * }
		 */
		static define(...args) {
			const [tagName, classref, elementDefinitionOptions] = args;
			if (elementDefinitionOptions && elementDefinitionOptions.extends) {
				this.tagName = elementDefinitionOptions.extends;
				// @ts-expect-error
				this.extendIsValue = tagName;
			} else {
				this.tagName = tagName;
			}
			customElements.define(tagName, classref, elementDefinitionOptions);
			return WC_createElement_bind(classref);
		}
	}
	return /** @type {RET} */ (/** @type {unknown} */ (MyClass));
}
